### ISSUE TITLE
“Client not configured” error

### ISSUE THREAD

**Issue by jnv** [cvut/kosapi_client.rb#13]
Somehow some specs are failing on top-level class which [should delegate calls to a client instance](https://github.com/cvut/kosapi_client.rb/blob/5bbfa52ead2e179c1ff8afe762540253e5f2a202/lib/kosapi_client/kosapi_client.rb#L29): https://travis-ci.org/cvut/kosapi_client.rb/jobs/53568760

This is happening even with isolated classes like [HttpClient](https://github.com/cvut/kosapi_client.rb/blob/5bbfa52ead2e179c1ff8afe762540253e5f2a202/spec/kosapi_client/http_client_spec.rb) – something is trying to call `to_str` on `KOSapiClient`. Frankly, I have no idea what's going on.

**Comment by jnv** [comment]
I see this is [addressed](https://github.com/cvut/kosapi_client.rb/pull/10/files#diff-16a14285a98a06335fb8e9b0ec9f08c1R42) in PR #10, but I wouldn't accept this hack.
It makes no sense that the code suddenly stopped working.

**Comment by DraCzris** [comment]
IMHO it is related to rspec mocking (instance_doble). Because when I've tried to swap instance doubles with real object instances it works. 

Maybe it is linked to https://github.com/mauricio/rspec-mocks/commit/80c740e5d7cd1959713cc13a84cc4f6c29155f2f

**Comment by jnv** [comment]
Yep, it occured to me that it might be some metaprogramming mindfuck caused by the fact that KOSapiClient module acts both as a namespace and a delegator for a client.

**Comment by DraCzris** [comment]
In this exact situation, that is not caused by metaprogramming. The problem here is that mocking service is invoking `to_str` method. Thats problem of rspec as in https://github.com/rspec/rspec-mocks/pull/577.

I've come around solution, which is less "hackier" in https://github.com/cvut/kosapi_client.rb/commit/9cb112fa31319b4e56593497cc791f2ba05aa86e of https://github.com/cvut/kosapi_client.rb/pull/10

**Comment by jnv** [comment]
Well, look at the date of that PR, this behaviour have been fixed in RSpec 3.0. Since we don't have a Gemfile.lock file, I guess this is some regression in newer RSpec (I run this on 3.2).

So the solutions are:

* Lock `rspec-mocks` dev dependency to an earlier version (in gemspec),
* introduce a workaround into the top-level module (which is fundamentally wrong because the module cannot be coerced into an equivalent string representation),
* remove implicit forwarding behaviour from the top-level module – I personally favour this option, because it removes complexity and nudges to a better practice (at the very slight price of inconvenience), however it is a breaking change.

**Comment by flexik** [comment]
In 0439b5b983b179b42927bce199a77e2a3d94b244 I have refactored client lazy initalization to be more robust. Before this change an error was thrown right away when the client was initialized without supplying API credentials. Now the client only throws an error when an API request is made without credentials.

It should fix this issue in a clean way and it also prevents other possible problems in the future.

**Comment by jnv** [comment]
:+1: Nice job, this is definitely an improvement though I'm still not a fan of the top-level stateful singleton `KOSapiClient` delegator.
